# Generated by Django 3.2.8 on 2021-12-30 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.conference')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo_url', models.CharField(max_length=100, unique=True)),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.conference')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.division')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img_url', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=4)),
                ('number', models.CharField(max_length=2)),
                ('min_per_game', models.FloatField()),
                ('pts_per_game', models.FloatField()),
                ('field_goal', models.FloatField()),
                ('reb_per_game', models.FloatField()),
                ('ast_per_game', models.FloatField()),
                ('rob_per_game', models.FloatField()),
                ('blk_per_game', models.FloatField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.team')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_pts', models.IntegerField()),
                ('visitor_pts', models.IntegerField()),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local', to='tracker.team')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor', to='tracker.team')),
            ],
        ),
    ]
