# Generated by Django 3.2.8 on 2021-12-30 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='rob_per_game',
            new_name='ft_ptg',
        ),
        migrations.AddField(
            model_name='player',
            name='plus_minus',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='stl_per_game',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='three_p_ptg',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='tov_per_game',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='abbreviation',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
    ]
