# Generated by Django 3.2.8 on 2022-01-01 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerSearchCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.player')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('fav_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.player')),
                ('fav_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.team')),
                ('searched_players', models.ManyToManyField(related_name='searched_players', through='tracker.PlayerSearchCounter', to='tracker.Player')),
            ],
        ),
        migrations.CreateModel(
            name='TeamSearchCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.profile')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.team')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='searched_teams',
            field=models.ManyToManyField(related_name='searched_teams', through='tracker.TeamSearchCounter', to='tracker.Team'),
        ),
        migrations.AddField(
            model_name='playersearchcounter',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.profile'),
        ),
    ]
