# Generated by Django 2.2.5 on 2022-01-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20220115_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='country',
            field=models.CharField(default='Country', max_length=100),
            preserve_default=False,
        ),
    ]
